site_name: Technical Documentation
site_dir: ../proactis-documentation.github.io
repo_url: https://github.com/proactis-documentation/ExampleApplications
repo_name: CodeExamples
copyright: '&copy; Proactis Ltd - All Rights Reserved'
site_author: David Betteridge
site_description: Technical documentation for the PROACTIS suite of products
edit_uri: null
extra_css:
    - css/extra.css
theme:
  name: null
  custom_dir: 'theme/mkdocs-material/material'
  language: en
  feature: []
  palette:
    primary: 'orange'
    accent: 'orange'
  font:
    text: 'Arial'
    code: 'Ubuntu Mono'
  logo: 'images/logo.png'
plugins: []

nav:
    - Invoice Capture:
        - 'Document Export' : 'invoicecapture/documentExport.md'
    - Marketplace: placeholder.md
    - P2P:
        - 'Budget Checking' : p2p/budgetchecking.md
        - 'Commitment Posting' : p2p/commitments.md
        - 'Configuration' :
            - 'Application Configuration' : p2p/applicationConfigurationSettings.md
            - 'Online Help' : p2p/help.md
        - 'Imaging Integration' :
            - 'Generic Imaging' : p2p/genericimaging.md
            - 'Custom Imaging' : p2p/customimaging.md
        - 'Invoice Posting' : p2p/invoicePosting.md
        - 'Import APIs' :
            - 'Acceptances': p2p/acceptanceGateway.md
            - 'Cancel Purchase Order': p2p/cancelPurhaseOrderGateway.md
            - 'Expenses': p2p/expensesGateway.md
            - 'Internal Invoices': p2p/internalInvoiceGateway.md
            - 'Master Data': p2p/masterData.md 
            - 'Purchase Credit Notes': p2p/purchaseCreditNoteGateway.md
            - 'Purchase Invoices': p2p/purchaseInvoiceGateway.md
            - 'Purchase Orders' : p2p/purchaseOrders.md
        - 'PunchOut and Marketplaces' : p2p/punchout.md
        - 'Nominal Validation' : p2p/nominalvalidation.md
        - 'Single Sign On (SSO)' : p2p/sso.md
        - 'Troubleshooting' : 'p2p/troubleshooting.md'     
        - 'Web site customisation' :
            - 'Addins' : 'p2p/addins.md'
            - 'Custom Tabs' : 'p2p/customtab.md'
    - 'ProContract': 
        - 'Proactis Product Integration': 
            - 'Source to Contract': 'procontract/PCtoS2CIntegration.md'
    - 'Source to Contract' :
            - 'Supplier Management': 's2c/srm.md'
            - 'Contract Management': 's2c/contracts.md'
            - 'Sourcing': 's2c/sourcing.md'
            - 'Users': 's2c/users.md'

markdown_extensions:
    - admonition: 
    - codehilite: